---
abstract: 'add code churn statistics to the changelog'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::DZil: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ChangeStats-Git
provides:
  Dist::Zilla::Plugin::ChangeStats::Git:
    file: lib/Dist/Zilla/Plugin/ChangeStats/Git.pm
    version: v0.1.3
  Dist::Zilla::Role::Author::YANICK::Changelog:
    file: lib/Dist/Zilla/Role/Author/YANICK/Changelog.pm
    version: v0.1.3
  Dist::Zilla::Role::Author::YANICK::RequireZillaRole:
    file: lib/Dist/Zilla/Role/Author/YANICK/RequireZillaRole.pm
    version: v0.1.3
requires:
  CPAN::Changes: 0.17
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::Plugin: 0
  Git::Repository: 0
  List::Util: 0
  Module::Load: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util: 0
  MooseX::Role::Parameterized: 0
  Perl::Version: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ChangeStats-Git
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-ChangeStats-Git/
  repository: https://github.com/yanick/Dist-Zilla-Plugin-ChangeStats-Git.git
version: 0.1.3
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
